### ISSUE TITLE
ToLowercase não funciona como esperado.

### ISSUE THREAD

**Issue by dscamargo** [pedrozocatelli/vscode-pedros-choice-keybinding#1]
Olá, testando sua extensão, verifiquei que o comando ALT+L não está funcionando como deveria.

Se possível, lançar uma correção o mais rápido possível.

Obrigado.

**Comment by pedrozocatelli** [comment]
> Olá, testando sua extensão, verifiquei que o comando ALT+L não está funcionando como deveria.
> 
> Se possível, lançar uma correção o mais rápido possível.
> 
> Obrigado.

Olá, foi verificado que é um bug mesmo, na versão 1.0.1 será corrigido.

Obrigado pelo feedback.

**Comment by pedrozocatelli** [comment]
Correção feita. Atualização 1.0.1
